[devent]

# the name of the devent
name="IPFS þing"

# where the event is happening
location="Reykjavík, Iceland"

# the dates the devent runs
dateStart = "2022-07-11"
dateEnd = "2022-07-17"

# a pithy tag line you want to show in the "hero/splash" part of the landing page
tagline="""
þing (n). thing, assembly, meeting, council. parliament.
"""

description="""
IPFS þing is a week-long gathering for the IPFS implementors community. There will be talks, workshops, discussion circles, hacking time, and more — all focused on advancing IPFS implementations.
"""


# a link to the devent website (what domain do you expect to use?)
link="https://2022.ipfs.camp"

# a link to RSVP for the event
rsvpLink="https://protocollabs.typeform.com/IPFSThing2022"

# a link to a logo image for the event
logo="ipfs-thing-logo.png"

# a link to a large res image for the hero/splash background.
# you likely want to use the devent location/city or something meaningful to the community
bgimg="background.png"

# the organizers of the devent (usually a group)
org="the IPFS Team"

# the website of the organizers
orglink="https://ipfs.io/team/"

# url for this event repo
repo="https://github.com/ipfs-shipyard/ipfs-thing-2022"

# list the participating teams.
# the format here is:
# [
#   ["Team Name", "https://team.org", "https://team.org/team-logo.jpg"],
# ]
teams = [
  ["Number Zero", "", "https://bafybeicftvbmvctgso22rtgvx43bql3g55p3x4a25bfnfkqqv3nwyfzewq.ipfs.dweb.link/number-zero-logo.png" ],
  ["Protocol Labs", "https://protocol.ai", "https://media.graphassets.com/e8bIG2apSUauy2dqK35W" ],
  ["PL Research", "https://research.protocol.ai", "https://research.protocol.ai/images/pl_research_logo.svg" ],
]

# this is a Frequently Asked Questions section.
#
# the format is:
# "Question here?" = """
# Answer here at length.
# """
[faq]

"What is IPFS þing?" = """
  Set in the inspiring and otherworldly landscape of Reykjavík, Iceland, IPFS þing is a collaborative workshop series for the IPFS implementors community. There will be talks, workshops, discussion circles, coworking and hacking time, and more — all focused on advancing IPFS implementations.
"""

"Who is it for?" = """
  This event brings together maintainers or core contributors of an IPFS implementation, ranging from production usage to working demo. If this describes you, please join! If you are unsure, email [ipfs-thing-2022@ipfs.io](mailto:ipfs-thing-2022@ipfs.io).

  If you are an IPFS user, tooling developer, collaborator, or curious community member, we enthusiastically invite you to IPFS Camp, an epic decentralized event organized by the community, for the community. Details on IPFS Camp are coming soon, and will be announced on [Twitter](https://twitter.com/ipfs).
"""

"All events are optional?!?" = """
Yes! This is a choose-your-own-adventure event, so please choose the track(s), sessions, arrival and departure dates, and activities that are interesting and relevant for *you*.

A bunch of us are actively working on putting together a fantastic schedule. We want your suggestions, feedback, and additions as Pull Requests & Issues [here](https://github.com/ipfs-shipyard/ipfs-thing-2022). Please jump in to help make this thing a thing that helps you."""

"I'm in! How do I participate?" = """
  Each implementation will demo in the IPFS Implementations Showcase on Day 2. However, that's just the beginning. Add yourself to the [Participating Teams](https://github.com/ipfs-shipyard/ipfs-thing-2022/edit/main/devent.toml) section of this website. Then, take a look at the latest sessions schedule. See an important track or session that's missing? Please propose it by [creating a PR to this repo](https://github.com/ipfs-shipyard/ipfs-thing-2022#add-your-event). You can also discuss an idea via [Github issue](https://github.com/ipfs-shipyard/ipfs-thing-2022/issues) before creating the PR.
"""

"Is there a cost to participate?" = """
  There is no charge to participate, and all meals during the event are provided. Participants (or their employers) are responsible for flights and accommodations. Several hotel blocks are being reserved and will be added here when confirmed; you are also free to book your own accommodations. 
"""

"Can I lead a track?" = """
Yes absolutely! Here's what's involved:

* Identify an IPFS-related topic that you know a thing or two about, and think others should care more about
* File a PR adding your track [here](http://github.com/ipfs-shipyard/ipfs-thing-2022/pulls/new)
* Recruit folks you collaborate regularly with to help shape the content of your track

You will have total control over the structure of your track. Morning of talks & afternoon of discussion? Go for it! Required reading before attendance? Sounds great.

Event organizers will work with you to help situate your track in the broader schedule, give feedback, and help to make your event great. We'll get you set up with AV gear, a room, and other logistical support as needed.
"""

"Can I request travel or childcare assistance?" = """
  Please email [ipfs-thing-2022@ipfs.io](mailto:ipfs-thing-2022@ipfs.io) and we will do our best to accommodate.
"""

"How do I contact the organizers?" = """
  You can reach out to us at [ipfs-thing-2022@ipfs.io](mailto:ipfs-thing-2022@ipfs.io).
"""

# schedule section config
[schedule]
description="""
All scheduled events are [optional](/#faq).
"""

# this is a footer section, with any footer links you may want.
# there are three sections: links (general), legal (policy + terms), and social.
[footer]

[footer.links]
"IPFS" = "https://ipfs.io"
"Event Github" = "https://github.com/ipfs-shipyard/ipfs-thing-2022"

[footer.legal]
"Privacy Policy" = "#"
"Terms & Conditions" = "#"

[footer.social]
twitter = "ipfs"
github = "ipfs"
