# the name of your track or event
name = "Your Event Name"

# the name of the group organizing the event
org = "Your Org"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@yourname"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://ipfs-althing.io"

# the start date of the event
date = "2022-07-11"

# how many days the event lasts (1 - N)
days = 2

# the event times (shows up in the event card)
times = "11:00 - 19:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "150"


# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the event.
# will show up when the user clicks the event card.
description = """
This is a day of technical talks and workshops about projects across computing and innovation systems. 
Check out the line up on the website. Social gathering 17:00 - 19:00.
"""
