# the name of your event
name = "Content Routing 1: Performance"

# the name of the group organizing the event
org = "PL Starfleet"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@jbenet" # @willscott

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
# website = ""

# the start date of the event
date = "2022-07-13"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00 - 17:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "150"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the event.
# will show up when the user clicks the event card.
description = """
If we can establish subsecond on average resolution across any CID, that would open a massive amount of adoption across IPFS
"""

[[timeslots]]
startTime="9:00"
speakers=[]
title="Welcome standup discussion"

[[timeslots]]
startTime="9:45"
speakers=["@jbenet"]
title="Content Routing Intro: Performance"

[[timeslots]]
startTime="10:30"
speakers=["@guseggert", "@gammazero", "@ajnavarro"]
title="State of content routing lightning talks"
description="@guseggert on IPFS DHT, @gammazero on Network Indexer, @ajnavarro on Reframe"

[[timeslots]]
startTime="11:00"
speakers=["@aschmahmann"]
title="Open Problem Identification and Alignment"

[[timeslots]]
startTime="11:30"
speakers=[]
type="break"
title=""

[[timeslots]]
startTime="11:45"
speakers=["@folex"]
title="Domain-specific IPFS content indexer with Aqua"

[[timeslots]]
startTime="12:15"
speakers=[]
title="Lunch Break"

[[timeslots]]
startTime="13:30"
speakers=[]
title="Open Slot"

[[timeslots]]
startTime="14:00"
speakers=["@vukolic", "@adlrocha"]
title="Hierarchical Consensus for Content Routing"

[[timeslots]]
startTime="14:45"
speakers=["@willscott"]
title="Network indexer roadmap"

[[timeslots]]
startTime="15:30"
speakers=["@masih"]
title="How to be an index provider"

[[timeslots]]
startTime="16:15"
speakers=[]
title="Break"

[[timeslots]]
startTime="16:30"
speakers=[]
title="Open Slot"
