# the name of your event
name = "Content Routing 2: Privacy"

# the name of the group organizing the event
org = "PL Starfleet"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@willscott"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
# website = ""

# the start date of the event
date = "2022-07-14"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00 - 17:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "150"


# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["WIP", "Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the event.
# will show up when the user clicks the event card.
description = """

"""

[[timeslots]]
startTime="09:00"
speakers=[]
title="Welcome standup discussion"

[[timeslots]]
startTime="09:45"
speakers=["@willscott"]
title="Content Routing Track Intro"

[[timeslots]]
startTime="10:00"
speakers=["@jbenet"]
title="Content Routing Intro: Privacy"
description="this is a description of the talk!"

[[timeslots]]
startTime="10:45"
speakers=["@tschorsch"]
title="Mechanism Lightning talks"
description="private set intersection for bitswap - @tschorsch, introductions to other mechanism - TBD"

[[timeslots]]
startTime="11:30"
speakers=[]
title="Break"

[[timeslots]]
startTime="11:45"
speakers=["@yiannis"]
title="Use cases for privacy in LibP2P"

[[timeslots]]
startTime="12:20"
speakers=["@elizabeth"]
title="Mixnets & Content Routing"

[[timeslots]]
startTime="12:40"
speakers=["@willscott"]
title="Funding Private Retrieval"
description = "Building towards a secure and performant system"

[[timeslots]]
startTime="13:00"
speakers=[]
title="Lunch Break"

[[timeslots]]
startTime="14:00"
speakers=["@Guillaume Michel"]
title="Double Hashing & Content Routing"

[[timeslots]]
startTime="14:45"
speakers=[""]
title="Private Information Retrieval & Content Routing"

[[timeslots]]
startTime="15:30"
speakers=[]
title="FHE, ZKPs & Content Routing"

[[timeslots]]
startTime="16:15"
speakers=[]
title="Break"

[[timeslots]]
startTime="16:30"
speakers=["Crypto Net Lab"]
title="Incentivization and content routing service differentiation"

