# the name of your track or event
name = "Browsers and The Web Platform"

# the name of the group organizing the event
org = "Browsers & Platforms team, Outercore"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@autonome"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://discuss.ipfs.io/t/2022-07-15-browsers-and-the-web-platform/14641"

# the start date of the event
date = "2022-07-15"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "13:00 - 17:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "20"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "Advanced"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Workshop"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
**The goal of this track is to craft a vision of IPFS in the web and browsers which is truly
 native to *both*, and a roadmap for achieving it.**

The web platform itself is a massive heterogenious ecosystem with unique challenges for new protocols (something which has never happened in a meaningful way) and stakeholders with particular requirements and a diverse vision of what the web actually is and can be. We need to define a way for IPFS be a deployment channel for HTML/JS/CSS, have a clearly defined security model for that content, such that both web standards and browser vendor stakeholders can reason about it and ultimately implement it.

Additionally, extra-web browser features and extensibility channels like browser extensions offer different capabilities, audiences and constraints. We must determine what the optimal strategy is for augmenting user experience of the regular web through the opportunities we have which are *adjacent* to it - eg connecting to local IPFS nodes, building browser extensions which read from or write to IPFS, or enabling users to move HTTP content to IPFS.

Finally, looking beyond existing browser channels, how can we redefine or leapfrog today's web using entirely new approaches such as removing existing browser metaphors or building mobile operating systems from the ground up with IPFS at the center.

This track is structured as an _intense_ half-day workshop. It will start with a
 brief introduction to frame our work, we'll hear lightning talks on use cases, 
then move to group discussion, using a design document for group iteration.

Bring your ideas, use-cases, needs and we'll redefine the track as needed before kicking off.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon

[[timeslots]]
startTime="13:00"
speakers=["@autonome"]
title="Intro to IPFS in Browsers & the Web"
description="""What's happened so far, who are the players, what's the landscape, 
what barriers exist, what feature gaps need closing, what to do next."""

[[timeslots]]
startTime="13:20"
speakers=["@lidel"]
title="State of IPFS and HTTP (TBD)"
description=""

[[timeslots]]
startTime="13:40"
speakers=["@RangerMauve?"]
title="Agregore `fetch()`, a multi-protocol abstraction"
description="""This talk will look at Peer to Peer URLs and how they can be used
in tandem with HTTP-like APIs within webapps using custom protocol handlers."""

[[timeslots]]
startTime="14:00"
speakers=["@fabricedesre"]
title="IPFS and Content Discovery"
description="""Incumbent Mobile OSes centralize content discovery in their app
stores. Let's explore how we could change that with IPFS!"""

[[timeslots]]
startTime="14:20"
speakers=["@meandavejustice"]
title="Manifest V3 and the road forward for IPFS browser extensions"
description=""

[[timeslots]]
startTime="14:40"
speakers=[]
title="Open Slot: Lightning talk"
description=""

[[timeslots]]
startTime="15:00"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="15:20"
speakers=[]
title="Workshop: Define an IPFS Application Model for the Web Platform"
description="""Work as a group to draft an application model for IPFS which 
aligns with web content models and APIs or redefines them as needed - such as
handling content loaded from a CID, publishing to IPFS directly from web content
or what an event model for IPFS content might be."""

[[timeslots]]
startTime="15:40"
speakers=["@marten-seemann"]
title="Challenges in Browser Connectivity"
description="""While full nodes can use transports like TCP and QUIC, this is not
an option for web browsers. Instead, we have to fall back to protocols like WebSocket,
WebTransport and WebRTC. And even for those, the browser API severly limits what we
can do."""

[[timeslots]]
startTime="16:20"
speakers=[]
title="Workshop: Threat modeling IPFS in web browsers"
description="Sprint exercise to identify common user tasks and enumerate possible threats against them."

[[timeslots]]
startTime="17:00"
speakers=[]
title="Workshop: Draft an IPFS network architecture plan for native browser integration"
description="""Work as a group to draft a network architecture plan which
integrates natively in existing web platform implementations"""
